//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelTrainingUsers
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LevelTrainingId { get; set; }
    
        public virtual LevelTraining LevelTraining { get; set; }
        public virtual Users Users { get; set; }
    }
}
