//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseWorkEntities1 : DbContext
    {
        public CourseWorkEntities1()
            : base("name=CourseWorkEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvaliableTime> AvaliableTime { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HorseGender> HorseGender { get; set; }
        public virtual DbSet<Horses> Horses { get; set; }
        public virtual DbSet<LevelTraining> LevelTraining { get; set; }
        public virtual DbSet<LevelTrainingHorses> LevelTrainingHorses { get; set; }
        public virtual DbSet<LevelTrainingUsers> LevelTrainingUsers { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PositionStable> PositionStable { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<SignTrainings> SignTrainings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
