//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignTrainings
    {
        public int Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> DateTrain { get; set; }
        public Nullable<int> TimeTrainId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> HorseId { get; set; }
    
        public virtual AvaliableTime AvaliableTime { get; set; }
        public virtual Horses Horses { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
